import React, { useState, useEffect } from 'react';
import { AlertCircle, Package, Send, Loader2, Camera, X, Plus, Minus, Users } from 'lucide-react';
import { SOSRequest, Severity, Status, Location } from '../types';
import { RescueStore } from '../services/firebase';
import { LocationPickerMap } from './LocationPickerMap';
import { VoiceRecorder } from './VoiceRecorder';

// Special needs options with icons
const SPECIAL_NEEDS_OPTIONS = [
  { id: 'pregnant', label: 'Pregnant', emoji: '🤰' },
  { id: 'elderly', label: 'Elderly', emoji: '👴' },
  { id: 'disabled', label: 'Disabled', emoji: '♿' },
  { id: 'infant', label: 'Infant', emoji: '👶' },
  { id: 'medical', label: 'Medical Condition', emoji: '💊' },
  { id: 'pet', label: 'Pet', emoji: '🐕' },
];

interface SOSFormProps {
  onCancel: () => void;
  onSuccess: (requestId: string) => void;
  userLocation: Location | null;
}

export const SOSForm: React.FC<SOSFormProps> = ({ onCancel, onSuccess, userLocation }) => {
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [severity, setSeverity] = useState<Severity>(Severity.CRITICAL);
  const [note, setNote] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [requestImages, setRequestImages] = useState<string[]>([]);
  const [editedLocation, setEditedLocation] = useState<Location | null>(null);
  const [address, setAddress] = useState<string>('');
  const [numberOfPeople, setNumberOfPeople] = useState(1);
  const [specialNeeds, setSpecialNeeds] = useState<string[]>([]);
  const [voiceNoteUrl, setVoiceNoteUrl] = useState<string | null>(null);

  // Initialize editedLocation when userLocation becomes available
  useEffect(() => {
    if (userLocation && !editedLocation) {
      setEditedLocation(userLocation);
    }
  }, [userLocation, editedLocation]);

  const handleLocationChange = (location: Location, newAddress: string) => {
    setEditedLocation(location);
    setAddress(newAddress);
  };

  // Convert file to base64
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const filesArray = Array.from(e.target.files);
      const remainingSlots = 5 - requestImages.length;

      if (remainingSlots <= 0) {
        alert("Maximum 5 images allowed.");
        return;
      }

      const filesToProcess = filesArray.slice(0, remainingSlots);

      // Convert files to base64 for persistence
      const base64Images = await Promise.all(
        filesToProcess.map((file: File) => fileToBase64(file))
      );

      setRequestImages(prev => [...prev, ...base64Images]);
    }
  };

  const removeImage = (index: number) => {
    setRequestImages(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editedLocation) {
      alert("We need your location to send help. Please enable GPS.");
      return;
    }

    setIsSubmitting(true);

    try {
      const newRequest: SOSRequest = {
        id: '', // Generated by Firestore
        contactName: name,
        contactPhone: phone,
        location: editedLocation,
        severity,
        status: Status.OPEN,
        note,
        timestamp: Date.now(),
        numberOfPeople,
        specialNeeds: specialNeeds.length > 0 ? specialNeeds : undefined,
        voiceNoteUrl: voiceNoteUrl || undefined,
        requestImageUrls: requestImages,
        messages: []
      };

      // Wrap the Firebase call in a race with a timeout
      // This prevents the UI from spinning forever if the DB connection hangs
      const timeoutPromise = new Promise((_, reject) =>
        setTimeout(() => reject(new Error("Connection timed out. Please check if your Firestore Database is created in the Firebase Console.")), 15000)
      );

      const newId = await Promise.race([
        RescueStore.addRequest(newRequest),
        timeoutPromise
      ]);

      onSuccess(newId as string);
    } catch (error: any) {
      console.error("Error submitting SOS:", error);

      // Provide helpful feedback based on common Firebase errors
      let errorMessage = error.message;
      if (errorMessage.includes("permission-denied")) {
        errorMessage = "Permission Denied. Please set Firestore Security Rules to 'Test Mode' in the Firebase Console.";
      } else if (errorMessage.includes("not-found")) {
        errorMessage = "Database not found. Please create the Firestore Database in the Firebase Console.";
      }

      alert(`Failed to send SOS: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="h-full flex flex-col bg-slate-900 text-white p-6 overflow-y-auto">
      <h2 className="text-2xl font-bold mb-6 text-red-500 flex items-center gap-2">
        <AlertCircle size={28} /> REQUEST HELP
      </h2>

      <form onSubmit={handleSubmit} className="flex-1 flex flex-col gap-6">

        {/* Severity Selection */}
        <div className="grid grid-cols-2 gap-4">
          <button
            type="button"
            onClick={() => setSeverity(Severity.CRITICAL)}
            className={`p-4 rounded-xl border-2 flex flex-col items-center gap-2 transition-all ${severity === Severity.CRITICAL
              ? 'bg-red-500/20 border-red-500 text-red-500'
              : 'bg-slate-800 border-slate-700 text-slate-400'
              }`}
          >
            <AlertCircle size={32} />
            <span className="font-bold">CRITICAL</span>
            <span className="text-xs">Life Threatening</span>
          </button>

          <button
            type="button"
            onClick={() => setSeverity(Severity.SUPPLIES)}
            className={`p-4 rounded-xl border-2 flex flex-col items-center gap-2 transition-all ${severity === Severity.SUPPLIES
              ? 'bg-orange-500/20 border-orange-500 text-orange-500'
              : 'bg-slate-800 border-slate-700 text-slate-400'
              }`}
          >
            <Package size={32} />
            <span className="font-bold">SUPPLIES</span>
            <span className="text-xs">Food / Water</span>
          </button>
        </div>

        {/* Number of People */}
        <div>
          <label className="block text-sm font-medium text-slate-400 mb-2">
            <Users size={16} className="inline mr-1" /> Number of People
          </label>
          <div className="flex items-center gap-4">
            <button
              type="button"
              onClick={() => setNumberOfPeople(Math.max(1, numberOfPeople - 1))}
              className="w-12 h-12 bg-slate-800 border border-slate-700 rounded-xl flex items-center justify-center text-white hover:bg-slate-700 transition"
            >
              <Minus size={20} />
            </button>
            <span className="text-3xl font-bold text-white w-16 text-center">{numberOfPeople}</span>
            <button
              type="button"
              onClick={() => setNumberOfPeople(Math.min(20, numberOfPeople + 1))}
              className="w-12 h-12 bg-slate-800 border border-slate-700 rounded-xl flex items-center justify-center text-white hover:bg-slate-700 transition"
            >
              <Plus size={20} />
            </button>
            <span className="text-slate-500 text-sm ml-2">people needing help</span>
          </div>
        </div>

        {/* Special Needs */}
        <div>
          <label className="block text-sm font-medium text-slate-400 mb-2">Special Needs (Optional)</label>
          <div className="grid grid-cols-3 gap-2">
            {SPECIAL_NEEDS_OPTIONS.map((option) => {
              const isSelected = specialNeeds.includes(option.id);
              return (
                <button
                  key={option.id}
                  type="button"
                  onClick={() => {
                    if (isSelected) {
                      setSpecialNeeds(specialNeeds.filter(n => n !== option.id));
                    } else {
                      setSpecialNeeds([...specialNeeds, option.id]);
                    }
                  }}
                  className={`p-3 rounded-xl border-2 flex flex-col items-center gap-1 transition-all text-sm ${isSelected
                    ? 'bg-blue-500/20 border-blue-500 text-blue-400'
                    : 'bg-slate-800 border-slate-700 text-slate-400 hover:border-slate-600'
                    }`}
                >
                  <span className="text-xl">{option.emoji}</span>
                  <span className="font-medium text-xs">{option.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Location Picker Map */}
        <div>
          <label className="block text-sm font-medium text-slate-400 mb-2">Your Location</label>
          <LocationPickerMap
            initialLocation={userLocation}
            onLocationChange={handleLocationChange}
          />
        </div>

        {/* Inputs */}
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-400 mb-1">Your Name</label>
            <input
              required
              type="text"
              value={name}
              onChange={e => setName(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-lg p-3 focus:border-red-500 outline-none transition"
              placeholder="e.g. John Doe"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-400 mb-1">Phone Number</label>
            <input
              required
              type="tel"
              value={phone}
              onChange={e => setPhone(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-lg p-3 focus:border-red-500 outline-none transition"
              placeholder="+1 234 567 890"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-400 mb-1">Photos of Situation (Optional, Max 5)</label>
            <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent">
              {requestImages.map((img, idx) => (
                <div key={idx} className="relative w-20 h-20 flex-shrink-0 rounded-lg overflow-hidden border border-slate-700">
                  <img src={img} alt={`Request ${idx}`} className="w-full h-full object-cover" />
                  <button
                    type="button"
                    onClick={() => removeImage(idx)}
                    className="absolute top-0 right-0 p-1 bg-black/60 text-white rounded-bl-lg hover:bg-red-600/80 transition"
                  >
                    <X size={12} />
                  </button>
                </div>
              ))}

              {requestImages.length < 5 && (
                <label className="w-20 h-20 flex-shrink-0 border-2 border-dashed border-slate-600 rounded-lg flex flex-col items-center justify-center text-slate-400 cursor-pointer hover:bg-slate-800 hover:border-slate-500 transition">
                  <Plus size={24} />
                  <span className="text-[10px]">Add</span>
                  <input
                    type="file"
                    accept="image/*"
                    multiple
                    className="hidden"
                    onChange={handleImageUpload}
                  />
                </label>
              )}
            </div>
            {requestImages.length === 0 && (
              <div className="text-xs text-slate-500 mt-1 italic">Adding photos helps rescuers prioritize.</div>
            )}
          </div>

          {/* Unified Situation Details - Voice OR Text */}
          <div>
            <label className="block text-sm font-medium text-slate-400 mb-2">Describe Your Situation</label>
            <div className="space-y-3">
              {/* Voice Option */}
              <VoiceRecorder
                onRecordingComplete={(audioBase64) => setVoiceNoteUrl(audioBase64)}
                hasRecording={!!voiceNoteUrl}
              />

              {/* Text Option */}
              <textarea
                value={note}
                onChange={e => setNote(e.target.value)}
                rows={3}
                className="w-full bg-slate-800 border border-slate-700 rounded-lg p-3 focus:border-red-500 outline-none transition"
                placeholder="Or type your situation here... (e.g. 3 people trapped on roof)"
              />

              <div className="text-xs text-slate-500 italic">
                {voiceNoteUrl && note ? '✓ Both voice and text will be sent' :
                  voiceNoteUrl ? '✓ Voice message will be sent' :
                    note ? '✓ Text message will be sent' :
                      'Record a voice message OR type your situation'}
              </div>
            </div>
          </div>
        </div>

        <div className="mt-auto pt-6 flex gap-3">
          <button
            type="button"
            onClick={onCancel}
            disabled={isSubmitting}
            className="flex-1 py-4 bg-slate-800 rounded-xl font-bold text-slate-400"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className="flex-[2] py-4 bg-red-600 rounded-xl font-bold text-white shadow-lg shadow-red-900/50 flex items-center justify-center gap-2"
          >
            {isSubmitting ? <Loader2 className="animate-spin" /> : <><Send size={20} /> SEND SOS</>}
          </button>
        </div>
      </form>
    </div>
  );
};